project:
  type: website
  output-dir: docs
  resources:
    - "assets/pdf/Kenji-Hayashi-CV.pdf"

website:
  title: Kenji Hayashi
  description: Personal website for Kenji Hayashi, PhD candidate in Ecology and Evolutionary Biology at UCLA
  image: assets/img/lasthenia-californica.jpg
  navbar:
    tools:
      - icon: github
        menu:
          - text: Source code
            url: https://github.com/kthayashi/kthayashi.github.io
          - text: Report an issue
            url: https://github.com/kthayashi/kthayashi.github.io/issues
    left:
      - href: index.qmd
        text: About
      - href: research/index.qmd
        text: Research
      - href: publications/index.qmd
        text: Publications
      - href: resources/index.qmd
        text: Resources
  page-footer:
    center: "© 2023 Kenji Hayashi | [License](https://github.com/kthayashi/kthayashi.github.io#license) | Built with [Quarto](https://quarto.org/)"
  site-url: https://kthayashi.github.io/
  open-graph: true

format:
  html:
    theme:
      - flatly
      - custom.scss
