project:
  type: website

website:
  title: "Kenji Hayashi"
  navbar:
    left:
      - href: index.qmd
        text: About
      - resources/index.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
