project:
  type: website

website:
  title: "Kenji Hayashi"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: publications
        text: Publications
      - href: resources
        text: Resources
  page-footer:
    center: "[License goes here] | [Acknowledgements](/acknowledgements)"

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
