project:
  type: website

website:
  title: Kenji Hayashi
  navbar:
    tools:
      - icon: github
        menu:
          - text: Source code
            url: https://github.com/kthayashi/website
          - text: Report an issue
            url: https://github.com/kthayashi/website/issues
    left:
      - href: index.qmd
        text: About
      - href: research/index.qmd
        text: Research
      - href: publications/index.qmd
        text: Publications
      - href: resources/index.qmd
        text: Resources
  page-footer:
    center: "© 2023 Kenji Hayashi | [License](https://github.com/kthayashi/website#license)"

format:
  html:
    theme:
      - flatly
      - custom.scss
