project:
  type: website

website:
  title: "Kenji Hayashi"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: publications/index.qmd
        text: Publications
      - href: resources/index.qmd
        text: Resources
  page-footer:
    center: "[License]() | [Acknowledgments](/acknowledgments/index.qmd)"

format:
  html:
    theme:
      - flatly
      - custom.scss
