project:
  type: website
  output-dir: docs

website:
  title: Kenji Hayashi
  navbar:
    tools:
      - icon: github
        menu:
          - text: Source code
            url: https://github.com/kthayashi/kthayashi.github.io
          - text: Report an issue
            url: https://github.com/kthayashi/website/kthayashi.github.io
    left:
      - href: index.qmd
        text: About
      - href: research/index.qmd
        text: Research
      - href: publications/index.qmd
        text: Publications
      - href: resources/index.qmd
        text: Resources
  page-footer:
    center: "© 2023 Kenji Hayashi | [License](https://github.com/kthayashi/kthayashi.github.io#license) | Built with [Quarto](https://quarto.org/)"

format:
  html:
    theme:
      - flatly
      - custom.scss
