project:
  type: website
  output-dir: docs
website:
  title: Kenji Hayashi
  description: >
    Personal website for Kenji Hayashi, Postdoctoral Associate in BioSciences
    at Rice University
  site-url: https://kthayashi.github.io
  navbar:
    left:
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
  page-footer:
    center: |
      © 2025 Kenji Hayashi.
      [Some rights reserved](https://github.com/kthayashi/kthayashi.github.io).  
      Built with [Quarto](https://quarto.org).
      Icons from [Font Awesome Free](https://fontawesome.com/license/free).
  open-graph:
    image: /assets/img/lasthenia-californica.jpg
    image-alt: A photo of Lasthenia californica
    locale: en
format:
  html:
    theme:
      - flatly
      - custom.scss
