---
title: "Resources"
toc: true
---

Over the years, I've bookmarked far too many resources that I can never seem to find when I actually need them. Rather than continuing to file these resources away in a corner of my web browser, I figured I could compile a running list here, both for myself and for anyone else who happens to come across this page. Please feel free to suggest any additions to this list by opening an [issue](https://github.com/kthayashi/kthayashi.github.io/issues) on the GitHub repo for this website. **Thank you to all the wonderful people out there who created these resources!**

## Academic

- [myIDP](https://myidp.sciencecareers.org/) by Cynthia Fuhrmann et al.
- [Society for the Advancement of Biology Research Education](https://saberbio.wildapricot.org/)
- [National Center for Faculty Development and Diversity](https://www.facultydiversity.org/)
- [Connected Papers](https://www.connectedpapers.com/)

## Blogs

- [Dynamic Ecology](https://dynamicecology.wordpress.com/) by Jeremy Fox et al.
- [Reflections on Papers Past](https://reflectionsonpaperspast.wordpress.com/) by Hari Sridhar
- [Publishable Stuff](https://www.sumsar.net/) by Rasmus Bååth

## Statistics & data science

### Books

- [Statistical Rethinking](https://xcelab.net/rm/statistical-rethinking/) by Richard McElreath
- [Statistical Rethinking with brms, ggplot2, and the tidyverse](https://bookdown.org/content/3890/) by Solomon Kurz
- [Bayesian Data Analysis](http://www.stat.columbia.edu/~gelman/book/) by Andrew Gelman et al.
- [Bayesian Data Analysis in Ecology with R and Stan](https://tobiasroth.github.io/BDAEcology/index.html) by Fränzi Korner-Nievergelt et al.
- [An Introduction to Bayesian Thinking](https://statswithr.github.io/book/) by Merlise Clyde et al.
- [An Introduction to Hierarchical Modeling](http://mfviz.com/hierarchical-models/) by Michael Freeman
- [Causal Inference in R](https://www.r-causal.org/) by Malcolm Barrett et al.
- [Applied Machine Learning Using mlr3 in R](https://mlr3book.mlr-org.com/) by Bernd Bischl et al.

### Websites

- [Probability Distribution Explorer](https://distribution-explorer.github.io/) by Justin Bois
- [A Visual Introduction to Hierarchical Models](http://mfviz.com/hierarchical-models/) by Michael Freeman
- [Seeing Theory](https://seeing-theory.brown.edu/) by Daniel Kunin et al.
- [Software Carpentry](https://software-carpentry.org/) by The Carpentries
- [Data Carpentry](https://datacarpentry.org/) by The Carpentries
- [Updating Data](https://www.updatingdata.org/) by Weecology
- [Best Practices for Data Visualisation](https://royal-statistical-society.github.io/datavisguide/) by the Royal Statistical Society
- [Real World Data Science](https://realworlddatascience.net/) by the Royal Statistical Society

### Posts

- [The Bayesian Counterpart of Pearson's Correlation Test](https://www.sumsar.net/blog/2013/08/bayesian-estimation-of-correlation/) by Rasmus Bååth
- [The Non-parametric Bootstrap as a Bayesian Model](https://www.sumsar.net/blog/2015/04/the-non-parametric-bootstrap-as-a-bayesian-model/) by Rasmus Bååth
- [Bayesian robust correlation with Stan in R](https://baezortega.github.io/2018/05/28/robust-correlation/) by Adrian Baez-Ortega

## Geospatial

- [Spatial Data Science with Applications in R](https://r-spatial.org/book/) by Edzer Pebesma & Roger Bivand
- [Spatial Data Science with R and "terra"](https://rspatial.org/index.html) by Robert Hijmans et al.

## Jobs

- [EcoEvoJobs 23-24](https://docs.google.com/spreadsheets/d/1Fvh1BZANNKsn8oVqqN2V4mQtKjpivU7fGqygNTTRAj8/edit#gid=54534292)
- [Natural Resources Job Board](https://wfscjobs.tamu.edu/job-board/) by Texas A&M University
- [NatureTech Jobs](https://naturetech.io/)

## R

### Books and manuals

- [The R Manuals](https://cran.r-project.org/manuals.html) by the R Development Core Team
- [Big Book of R](https://www.bigbookofr.com/) by Oscar Baruffa
- [swirl: Learn R, in R](https://swirlstats.com/) by Team swirl
- [ggplot2: Elegant Graphics for Data Analysis (3e)](https://ggplot2-book.org/) by Hadley Wickham et al.
- [R for Data Science (2e)](https://r4ds.hadley.nz/) by Hadley Wickham et al.
- [Mastering Shiny](https://mastering-shiny.org/) by Hadley Wickham
- [Engineering Production-Grade Shiny Apps](https://engineering-shiny.org/) by Colin Fay et al.
- [shinyapps.io User Guide](https://docs.posit.co/shinyapps.io/index.html) by shinyapps.io Team
- [R Packages (2e)](https://r-pkgs.org/) by Hadley Wickham & Jennifer Bryan
- [Licensing R](https://thinkr-open.github.io/licensing-r/) by Colin Fay
- [Advanced R (2e)](https://adv-r.hadley.nz/) by Hadley Wickham
- [The tidyverse Style Guide](https://style.tidyverse.org/) by Hadley Wickham
- [Posit Cheatsheets](https://posit.co/resources/cheatsheets/) by Posit
- [R Color Palettes](https://github.com/EmilHvitfeldt/r-color-palettes) by Emil Hvitfeldt
- [R Color Cheatsheet](https://www.nceas.ucsb.edu/sites/default/files/2020-04/colorPaletteCheatsheet.pdf) by NCEAS
- [Awesome ggplot2](https://github.com/erikgahner/awesome-ggplot2) by Erik Gahner Larsen et al.
- [R Weekly](https://rweekly.org/) by R Weekly

### Packages

- [tidyverse](https://tidyverse.tidyverse.org/) by Hadley Wickham et al.
- [targets](https://docs.ropensci.org/targets/) by William Michael Landau

## Remote sensing

- [Applied Remote Sensing Program (ARSET)](https://appliedsciences.nasa.gov/what-we-do/capacity-building/arset) by NASA

## Reproducible research

- [Quarto Guide](https://quarto.org/docs/guide/) by Posit
- [R Markdown: The Definitive Guide](https://bookdown.org/yihui/rmarkdown/) by Yihui Xie et al.
- [R Markdown Cookbook](https://bookdown.org/yihui/rmarkdown-cookbook/) by Yihui Xie et al.
- [R Markdown for writing reproducible scientific papers](https://libscie.github.io/rmarkdown-workshop/handout.html) by Mike Frank & Chris Hartgerink
- [Academic publications with R Markdown](https://danovando.github.io/publications-with-rmarkdown/presentations/pubs-with-rmarkdown#1) by Dan Ovando
- [The Plain Person's Guide to Plain Text Social Science](https://kieranhealy.org/publications/plain-person-text/) by Kieran Healy
- [Metadata and describing data](https://data.research.cornell.edu/data-management/storing-and-managing/metadata/) by Cornell Data Services
- [Guide to writing "readme" style metadata](https://data.research.cornell.edu/data-management/sharing/readme/) by Cornell Data Services

## Web development

- [Creating your personal website using Quarto](https://ucsb-meds.github.io/creating-quarto-websites/) by Sam Csik
- [Customizing Quarto websites](https://ucsb-meds.github.io/customizing-quarto-websites/#/title-slide) by Sam Csik
- [Adding a blog to your existing Quarto website](https://samanthacsik.github.io/posts/2022-10-24-quarto-blogs/) by Sam Csik
